server:
  port: 8761
spring:
  application:
    name: eureka
eureka:
  server:
    # 是否开启自我保护模式，默认为true
    enable-self-preservation: true
    #续期时间，即扫描失效服务的间隔时间（缺省为60*1000ms）
    eviction-interval-timer-in-ms: 10000
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: false
    # 设置是否将自己作为客户端注册到注册中心（缺省true）
    register-with-eureka: true
