spring:
  application:
    # 服务名称尽量用-，不要用_，不要用特殊字符
    name: customer
cloud:
  nacos:
    discovery:
      # 指定nacos server的地址
      server-addr: localhost:8848

server:
  port: 8011
customer:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
ribbon:
  # ribbon饥饿加载
  eager-load:
    enabled: true
    clients: customer
logging:
  level:
    com.customer.configuration.ProductorFeignConfiguration:debug

feign:
  client:
    config:
      # 想要调用的微服务的名称
      productor:
        loggerLevel:full