server:
  port: 8011

spring:
  application:
    # 服务名称尽量用-，不要用_，不要用特殊字符
    name: customer
  cloud:
    nacos:
      discovery:
        # 指定nacos server的地址
        server-addr: localhost:8848
    # 向sentinel控制台注册服务
    sentinel:
      transport:
        # port端口配置会在应用对应的机器上启动一个 Http Server，该 Server 会与 Sentinel 控制台做交互。比如 Sentinel 控制台添加了一个限流规则，会把规则数据 push 给这个 Http Server 接收，Http Server 再将规则注册到 Sentinel 中。
        port: 8719
        dashboard: localhost:8080
      # 取消懒加载
      eager: true
management:
  endpoints:
    web:
      exposure:
        include: '*'


customer:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
ribbon:
  ReadTimeout: 1
  ConnectTimeout: 1
  # ribbon饥饿加载
  eager-load:
    enabled: true
    clients: customer
feign:
  client:
    config:
      # 全局配置
      default:
        loggerLevel: full
        connectTimeout: 1000
        readTimeout: 1000

  httpclient:
    connection-timeout: 2000



#logging:
#  level:
#    com.customer.configuration.GlobalFeignConfiguration:debug
