spring:
  application:
    name: multidatabase

productor:
  datasource:
    url:jdbc: mysql://localhost:3306/productor
    username: root
    password: 123456

customer:
  datasource:
    url:jdbc: mysql://localhost:3306/customer
    username: root
    password: 123456