server:
  port: 8040
spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    gateway:
      discovery:
        locator:
          # 允许gateway通过服务发现组件找到其他的微服务
          enabled: true
      routes:
        - id: between_time
          uri: lb://customer
          predicates:
            - TimeBetween= 1:00 PM,11:00 PM
management:
  endpoints:
    web:
      exposure:
        include: '*'

