server:
  port: 8001
spring:
  application:
    # 服务名称尽量用-，不要用_，不要用特殊字符
    name: productor
  cloud:
    nacos:
      discovery:
        # 指定nacos server的地址
        server-addr: localhost:8848
    # 向sentinel控制台注册服务
    sentinel:
      transport:
        # port端口配置会在应用对应的机器上启动一个 Http Server，该 Server 会与 Sentinel 控制台做交互。比如 Sentinel 控制台添加了一个限流规则，会把规则数据 push 给这个 Http Server 接收，Http Server 再将规则注册到 Sentinel 中。
        port: 8719
        dashboard: localhost:8080
      # 取消懒加载
        eager: true
  management:
    endpoints:
      web:
        exposure:
          include: '*'

productor:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
ribbon:
  # ribbon饥饿加载
  eager-load:
    enabled: true
    clients: productor

#  cloud:
#    nacos:
#      metadata:
#        # 自己这个实例的版本
#        version: v1
#        # 允许调用的提供者版本
#        target-version: v1
#  cloud:
#    nacos:
#      discovery:
#        # 指定nacos server的地址
#        server-addr: localhost:8848
#        cluster-name: BJ
        # namespace: 56116141-d837-4d15-8842-94e153bb6cfb
#    javase.redis.sentinel:
#      filter:
#        # 打开/关闭掉对Spring MVC端点的保护
#        enabled: true
#      transport:
#        # 指定sentinel 控制台的地址
#        dashboard: localhost:8080
#    stream:
#      rocketmq:
#        binder:
#          name-server: 127.0.0.1:9876
#        bindings:
#          output:
#            producer:
#              transactional: true
#              group: tx-add-bonus-group
#      bindings:
#        output:
#          # 用来指定topic
#          destination: add-bonus


#  main:
#    allow-bean-definition-overriding: true

#logging:
#  level:
#    com.itmuch.contentcenter.feignclient.UserCenterFeignClient: debug
#    com.alibaba.nacos: error
#feign:
#  javase.redis.sentinel:
#
#    # 为feign整合sentinel
#    enabled: true
#  client:
#    config:
#      # 全局配置
#      default:
#        loggerLevel: full
#        requestInterceptors:
#          - com.itmuch.contentcenter.feignclient.interceptor.TokenRelayRequestIntecepor
#  httpclient:
#    # 让feign使用apache httpclient做请求；而不是默认的urlconnection
#    enabled: true
#    # feign的最大连接数
#    max-connections: 200
#    # feign单个路径的最大连接数
#    max-connections-per-route: 50

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
#resttemplate:
#  javase.redis.sentinel:
#    # 设置成false，表示关闭@SentinelRestTemplate注解
#    enabled: true

#jwt:
#  secret: aaaaaaabbbbbbcccccdddddaaaaaaabbbbbbcccccdddddaaaaaaabbbbbbcccccddddd
#  # 有效期，单位秒，默认2周
#  expire-time-in-second: 1209600

rocketmq:
  name-server: localhost:9876